name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H 13.61.182.189 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@13.61.182.189 << 'EOF'
            echo "🧹 Stopping and removing existing container..."
            sudo docker rm -f backend || true

            echo "🗑 Removing old image..."
            sudo docker rmi karoshalex0873/skillmatch_ai || true

            echo "📦 Pulling latest image..."
            sudo docker pull karoshalex0873/skillmatch_ai

            echo "🚀 Starting new container..."
            sudo docker run -d -p 80:80 --name backend karoshalex0873/skillmatch_ai

            echo "✅ Deployment done!"
            sudo docker ps
          EOF
