name: CI - Test Express Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # or whatever version you're using

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
